### ISSUE TITLE
`A` prefix

### ISSUE THREAD

**Issue by peteshand** [RobertBorghese/Haxe-UnrealEngine5#10]
I've just tested the latest update. seeing good improvements.
Though one issue I'm see is to do with the `A` prefix.. I had similar issues a while back, but they resolved..
Anyways this time I've pulled a fresh copy of the sample project and when I compile the output of the MyActor.h has
`#include "AMyActor.h` on line 18 
![image](https://user-images.githubusercontent.com/139457/194321570-587e2813-b471-46bc-8ad9-1b252cc45506.png)
I'm currently working around this by manually removing the `A`
Are you seeing the same thing?

**Comment by SomeRanDev** [comment]
Yes! Sorry about this again! Literally just fixed this also with new commit. Apologies for all these issues that keep occurring whenever I make a bunch of changes,
