### ISSUE TITLE
Linux: -Werror,-Wreorder-ctor

### ISSUE THREAD

**Issue by peteshand** [RobertBorghese/Haxe-UnrealEngine5#18]
I've been blocked building on Linux for the past few days with errors along the lines of: 
```
error: field 'type' will be initialized after field 'valObject' [-Werror,-Wreorder-ctor]
```

I'm looking into a solution, but though I'd log the error / progress here.

The root cause seems to be that Unreal has more strict compile requirements than hxcpp.
I've been looking for a way to relax unreal's compiler requirements without changing the build process (as in my case I don't have access to this), however am yet to find a solution.

I'm temped to look at updating the `hxpp-include` directory to resolve the issue there, however not sure if there is the best approach.

Let me know if you have any thoughts

**Comment by SomeRanDev** [comment]
I agree. Unless there's something you can do in the `build.cs` file, you really don't have a choice. :(

The hxcpp-include folder already includes modifications because of other issues like this, so more modifications wouldn't be an issue, though if possible, keep them to a minimal so they aren't a hassle to resolve when updating to future versions of hxcpp. If possible, make the changes a pull request on hxcpp as well so they may add it to a future version. That's what I plan to do with the modifications I've made once I get a bit more time. XD

**Comment by SomeRanDev** [comment]
WAIT! Actually I forgot about this, but I also have a system for disabling certain errors. If you can get the error code for that error you're experiencing, place it here.
https://github.com/RobertBorghese/Haxe-UnrealEngine5/blob/4d6ef15936ec3de0d993b831d62a2903ac248a78/SampleProject/Haxe/BuildScripts/CopyHxOutputToSourceFolder.hx#L32

This is how I resolved the errors that occurred in regards to shadowing. You can still see them commented out. Just add your own error codes there and check if it works?

**Comment by peteshand** [comment]
Ok, thanks for the info.

I've managed to resolve the `[-Werror,-Wreorder-ctor]` via two metheds.

The first was to just update the `hxcpp-include` source, in most cases it was just a matter of reordering the definition of variables. This is good in that it resolves the issue, but yeah not ideal to be making changes to these files.

Since you're last comment I've taken a look at the `errorsToDisable` array.
However I'm not sure what the codes are for -Werror and -Wreorder-ctor
Based on this: https://learn.microsoft.com/en-us/cpp/preprocessor/warning?view=msvc-170 it sounds like these codes may only be for the mcvs compiler only?

It seems like the linux build system is using clang.

but following the same line of thinking I've managed also resolve/ignore the error by adding the below line to 'HaxeCompatibility.cpp'
```
#pragma clang diagnostic ignored "-Wreorder-ctor"
```

Still not ideal because I'm adding `clang` specific code. I'm not sure if this should be added to the sample project or not? Maybe within a comment block?
