### ISSUE TITLE
TReturnType UClass UObject

### ISSUE THREAD

**Issue by peteshand** [RobertBorghese/Haxe-UnrealEngine5#2]
Hey where are TReturnType, UClass, UObject defined?
I'm getting errors for each of these along the lines of:

`src/ue/FObjectInitializer.hx:8: characters 117-128 : Type not found : TReturnType`

`src/ue/FObjectInitializer.hx:10: characters 39-45 : Type not found : UClass`

`src/ue/FObjectInitializer.hx:8: characters 57-64 : Type not found : UObject`

**Comment by SomeRanDev** [comment]
Whoops! Sorry about that. Forgot to update the handwritten files after after last push. TReturnType is a template argument, and the U prefix needs to be removed from the other classes. I'll update the FObjectInitializer.hx in a sec!

**Comment by SomeRanDev** [comment]
Should be fixed with [fe9dd86](https://github.com/RobertBorghese/Haxe-UnrealEngine5/commit/fe9dd860eb404057c86c0a07f367ab780e91bf88)

**Comment by peteshand** [comment]
Thanks, that's working now. The sample haxe project now compiles and create:
`Source/HaxeProject/HaxeOutput/AMyActor.cpp` 
and 
`Source/HaxeProject/HaxeOutput/AMyActor.h`

However when building the `HaxeProject` sample unreal project I get the following error:
SampleProject\Source\HaxeProject\HaxeOutput\AMyActor.h(34): error C2338: You have to define AMyActor::AMyActor() or AMyActor::AMyActor(const FObjectInitializer&). This is required by UObject system to work correctly.

Have you seen this before?

Here is my output if it helps:
[AMyActor.zip](https://github.com/RobertBorghese/Haxe-UnrealEngine5/files/9611698/AMyActor.zip)

**Comment by SomeRanDev** [comment]
Sorry for the delayed response! Hmmm, maybe I missed something... I did get it to compile at one point, I'd have to take another look at it. Just to be clear, atm this project is still in very early infancy, all development time is spent fighting to get things compiling in the first place, and there's no guarantee anything will work anytime soon. Next time I get a lot of time to work on this project, I'm going to drastically change my strategy from what's currently posted anyway, so I wouldn't get too invested into making the current sample work. Apologies!! (;^_^)

Though, if you encounter any issues with the externs, of course be sure to post another Issue! I really appreciate your time looking through this project, I apologize that it isn't in a compliable form yet. :)
