### ISSUE TITLE
haxe.Json

### ISSUE THREAD

**Issue by peteshand** [RobertBorghese/Haxe-UnrealEngine5#8]
I've been playing with `haxe.Json` this evening, as it seems like a good goal due to the fact that is has more or less all the basic types. however I'm running into this error.

```
Module.HaxeCompatibility.cpp.obj : error LNK2001: unresolved external symbol "public: virtual class Dynamic __cdecl hx::EnumBase_obj::__GetItem(int)const " (?__GetItem@EnumBase_obj@hx@@UEBA?AVDynamic@@H@Z)
```

Any tips for troubleshooting this?

**Comment by SomeRanDev** [comment]
Yes! This was a mistake I made. The hxcpp headers I use are from the current github, but Haxe compiles with an earlier release of hxcpp. I actually just committed a fix for this since I encountered it myself, give it a go!

**Comment by peteshand** [comment]
nice one.. I've just tested and the above error has gone!
I have spotted one other thing to do with the `A` prefix, but I'll pop it in a separate thread
